/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated.requests'
import { Route as AuthenticatedOvertimeRouteImport } from './routes/_authenticated.overtime'
import { Route as AuthenticatedLeaveBalanceRouteImport } from './routes/_authenticated.leave-balance'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AuthenticatedRequestsNewRouteImport } from './routes/_authenticated.requests.new'
import { Route as AdminAdminRequestsRouteImport } from './routes/_admin.admin.requests'
import { Route as AdminAdminPoliciesRouteImport } from './routes/_admin.admin.policies'
import { Route as AdminAdminEmployeesRouteImport } from './routes/_admin.admin.employees'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOvertimeRoute = AuthenticatedOvertimeRouteImport.update({
  id: '/overtime',
  path: '/overtime',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveBalanceRoute =
  AuthenticatedLeaveBalanceRouteImport.update({
    id: '/leave-balance',
    path: '/leave-balance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedRequestsNewRoute =
  AuthenticatedRequestsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AdminAdminRequestsRoute = AdminAdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPoliciesRoute = AdminAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEmployeesRoute = AdminAdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/leave-balance': typeof AuthenticatedLeaveBalanceRoute
  '/overtime': typeof AuthenticatedOvertimeRoute
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/policies': typeof AdminAdminPoliciesRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/leave-balance': typeof AuthenticatedLeaveBalanceRoute
  '/overtime': typeof AuthenticatedOvertimeRoute
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/admin/employees': typeof AdminAdminEmployeesRoute
  '/admin/policies': typeof AdminAdminPoliciesRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/leave-balance': typeof AuthenticatedLeaveBalanceRoute
  '/_authenticated/overtime': typeof AuthenticatedOvertimeRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/_admin/admin/employees': typeof AdminAdminEmployeesRoute
  '/_admin/admin/policies': typeof AdminAdminPoliciesRoute
  '/_admin/admin/requests': typeof AdminAdminRequestsRoute
  '/_authenticated/requests/new': typeof AuthenticatedRequestsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/home'
    | '/leave-balance'
    | '/overtime'
    | '/requests'
    | '/admin/employees'
    | '/admin/policies'
    | '/admin/requests'
    | '/requests/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/home'
    | '/leave-balance'
    | '/overtime'
    | '/requests'
    | '/admin/employees'
    | '/admin/policies'
    | '/admin/requests'
    | '/requests/new'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_admin/admin'
    | '/_authenticated/home'
    | '/_authenticated/leave-balance'
    | '/_authenticated/overtime'
    | '/_authenticated/requests'
    | '/_admin/admin/employees'
    | '/_admin/admin/policies'
    | '/_admin/admin/requests'
    | '/_authenticated/requests/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overtime': {
      id: '/_authenticated/overtime'
      path: '/overtime'
      fullPath: '/overtime'
      preLoaderRoute: typeof AuthenticatedOvertimeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave-balance': {
      id: '/_authenticated/leave-balance'
      path: '/leave-balance'
      fullPath: '/leave-balance'
      preLoaderRoute: typeof AuthenticatedLeaveBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/requests/new': {
      id: '/_authenticated/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthenticatedRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_admin/admin/requests': {
      id: '/_admin/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminAdminRequestsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/policies': {
      id: '/_admin/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminAdminPoliciesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/employees': {
      id: '/_admin/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminAdminEmployeesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminEmployeesRoute: typeof AdminAdminEmployeesRoute
  AdminAdminPoliciesRoute: typeof AdminAdminPoliciesRoute
  AdminAdminRequestsRoute: typeof AdminAdminRequestsRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminEmployeesRoute: AdminAdminEmployeesRoute,
  AdminAdminPoliciesRoute: AdminAdminPoliciesRoute,
  AdminAdminRequestsRoute: AdminAdminRequestsRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRequestsRouteChildren {
  AuthenticatedRequestsNewRoute: typeof AuthenticatedRequestsNewRoute
}

const AuthenticatedRequestsRouteChildren: AuthenticatedRequestsRouteChildren = {
  AuthenticatedRequestsNewRoute: AuthenticatedRequestsNewRoute,
}

const AuthenticatedRequestsRouteWithChildren =
  AuthenticatedRequestsRoute._addFileChildren(
    AuthenticatedRequestsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLeaveBalanceRoute: typeof AuthenticatedLeaveBalanceRoute
  AuthenticatedOvertimeRoute: typeof AuthenticatedOvertimeRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLeaveBalanceRoute: AuthenticatedLeaveBalanceRoute,
  AuthenticatedOvertimeRoute: AuthenticatedOvertimeRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
